<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-84KGOP9" ignored="0" name="Yahoo Sign In Test" tests="1" failures="1" timestamp="16 Jan 2019 15:59:50 GMT" time="105.556" errors="0">
  <testcase name="yahooSignIn" time="99.515" classname="com.pge.hybrid.testcases.yahoosuite.YahooSignIn">
    <failure type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
at com.pge.hybrid.driver.DriverScript.executeKeywords(DriverScript.java:47)
at com.pge.hybrid.testcases.yahoosuite.YahooSignIn.yahooSignIn(YahooSignIn.java:23)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: The following asserts failed:
Object Not Found yahoo_pwd_id
at com.pge.hybrid.keywords.GenericKeywords.reportFailure(GenericKeywords.java:374)
at com.pge.hybrid.keywords.GenericKeywords.getObject(GenericKeywords.java:307)
at com.pge.hybrid.keywords.AppKeywords.yahooLogin(AppKeywords.java:61)
... 26 more
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- yahooSignIn -->
</testsuite> <!-- Yahoo Sign In Test -->
